[versions]

androidGradlePlugin = "8.3.1"
androidxActivity = "1.7.2"
androidxAppCompat = "1.6.1"
androidxArchCore = "2.2.0"
androidxCollection = "1.2.0"
androidxComposeBom = "2023.06.01"
androidxConstraintLayout = "2.1.4"
androidxCore = "1.10.1"
androidxFragment = "1.6.1"
androidxHilt = "1.0.0"
androidxLegacySupportV4 = "1.0.0"
androidXLifecyle = "2.6.1"
androidxNavigation = "2.6.0"
androidxPreference = "1.2.0"
androidxRoom = "2.5.2"
androidxSqlite = "2.3.1"
androidxSwipeRefreshLayout = "1.1.0"
androidxTestEspresso = "3.5.1"
androidxTestExt = "1.1.5"
androidxTestExtTruth = "1.5.0"
androidxTestMonitor = "1.6.1"
androidxTestOrchestrator = "1.4.2"
androidxTestRules = "1.5.0"
androidxTestRunner = "1.5.2"

composeKotlinCompilerExtensionVersion = "1.5.1"
crashlyticsPlugin = "2.9.7"

desugar = "2.0.3"

firebaseBom = "32.2.0"

googleAndroidMaterial = "1.9.0"
googleAndroidPlayIntegrity = "1.2.0"
googleCodeGson = "2.10.1"
googleDaggerHilt = "2.47"
googleServices = "4.3.15"
googleTruth = "1.1.5"

jacoco = "0.8.11"
javaxAnnotationApi = "1.3.2"
jetbrainsKotlinx = "1.7.3"
junit = "4.13.2"
junit5 = "5.10.2"

navigationSafeArgs = "2.6.0"

kotlin = "1.9.0"
kspPlugin = "1.9.0-1.0.13"

timber = "5.0.1"

mockk = "1.13.9"

robolectric = "4.11.1"

sonarqubePlugin = "4.3.0.3225"
squareupMoshi = "1.15.0"
squareupOkhttp3 = "4.11.0"
squareupRetrofit2 = "2.9.0"

compileSdk = "34"
minSdk = "24"
targetSdk = "34"

[libraries]

#android tools
android-tools-desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar" }
#android tools build (plugin com.android.application)
android-tools-build-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
android-tools-build-gradle-api = { group = "com.android.tools.build", name = "gradle-api", version.ref = "androidGradlePlugin" }
#androidx activity
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidxActivity" }
#androix compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-compiler = { group = "androidx.compose.compiler", name = "compiler", version.ref = "composeKotlinCompilerExtensionVersion" }
## Material Design 3
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
## or material 2
androidx-compose-material = { group = "androidx.compose.material", name = "material" }
## or skip Material Design and build directly on top of foundational components
androidx-compose-fundation = { group = "androidx.compose.foundation", name = "foundation" }
## or only import the main APIs for the underlying toolkit systems,
## such as input and measurement/layout
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
## androidx compose graphics
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
## Android Studio Preview support
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
## compose  UI Tests
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
## Optional - Included automatically by material, only add when you need
## the icons but not the material library (e.g. when using Material3 or a
##  custom design system based on Foundation)
androidx-compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
## Optional - Add full set of material icons
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
## Optional - Add window size utils
androidx-compose-material3-window-size = { group = "androidx.compose.material3", name = "material3-window-size-class" }
## Optional - Integration with activities
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
## Optional - Integration with ViewModels
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidXLifecyle" }
## Optional - Integration with LiveData
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime-livedata" }
## Optional - Integration with RxJava
androidx-compose-runtime-rxjava2 = { group = "androidx.compose.runtime", name = "runtime-rxjava2" }
#androidx appcompat
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
#androidx arch core
androidx-arch-core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "androidxArchCore" }
#androidx collection
androidx-collection-ktx = { group = "androidx.collection", name = "collection-ktx", version.ref = "androidxCollection" }
#androidx constraint layout
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintLayout" }
#androidx core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
#androidx fragment
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidxFragment" }
androidx-fragment-testing = { group = "androidx.fragment", name = "fragment-testing", version.ref = "androidxFragment" }
#androidx hilt
androidx-hilt-navigation-fragment = { group = "androidx.hilt", name = "hilt-navigation-fragment", version.ref = "androidxHilt" }
#androidx legacy
androidx-legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "androidxLegacySupportV4" }
#androidx lifecycle
androidx-lifecyle-livedata-core-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-core-ktx", version.ref = "androidXLifecyle" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidXLifecyle" }
androidx-lifecyle-reactivestreams-ktx = { group = "androidx.lifecycle", name = "lifecycle-reactivestreams-ktx", version.ref = "androidXLifecyle" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidXLifecyle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidXLifecyle" }
#androidx navigation
androidx-navigation-dynamic-features-fragment = { group = "androidx.navigation", name = "navigation-dynamic-features-fragment", version.ref = "androidxNavigation" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidxNavigation" }
androidx-navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "androidxNavigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidxNavigation" }
#androidx preference
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "androidxPreference" }
#androidx room
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidxRoom" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
#androidx sqlite
androidx-sqlite-ktx = { group = "androidx.sqlite", name = "sqlite-ktx", version.ref = "androidxSqlite" }
#androidx swiperefreshlayout
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "androidxSwipeRefreshLayout" }
#androidx test espresso
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxTestEspresso" }
#androidx test ext
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExt" }
#androidx test ext truth
androidx-test-ext-truth = { group = "androidx.test.ext", name = "truth", version.ref = "androidxTestExtTruth" }
#androidx test monitor
androidx-test-monitor = { group = "androidx.test", name = "monitor", version.ref = "androidxTestMonitor" }
#androidx test orchestrator
androidx-test-orchestrator = { group = "androidx.test", name = "orchestrator", version.ref = "androidxTestOrchestrator" }
#androidx test rules
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules" }
#androidx test runner
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }

#firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-analytics-ktx = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-crashlytics-ktx = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }

#google android material
google-android-material = { group = "com.google.android.material", name = "material", version.ref = "googleAndroidMaterial" }
#google android play integrity
google-android-play-integrity = { group = "com.google.android.play", name = "integrity", version.ref = "googleAndroidPlayIntegrity" }
#google code gson
google-code-gson = { group = "com.google.code.gson", name = "gson", version.ref = "googleCodeGson" }
#google dagger hilt
google-dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "googleDaggerHilt" }
google-dagger-hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "googleDaggerHilt" }
google-dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "googleDaggerHilt" }
#google truth
google-truth = { group = "com.google.truth", name = "truth", version.ref = "googleTruth" }

#javax annotation
javax-annotation-api = { group = "javax.annotation", name = "javax.annotation-api", version.ref = "javaxAnnotationApi" }
#jetbrains kotlin
jetbrains-kotlin-stdlib-jdk8 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
#jetbrains kotlinx
jetbrains-kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "jetbrainsKotlinx" }
jetbrains-kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "jetbrainsKotlinx" }
#junit

junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher"}
junit5Bom = { group = "org.junit", name = "junit-bom", version.ref = "junit5"}
junit5 = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit5-vintage = { group = "org.junit.vintage", name = "junit-vintage-engine" }
#mockk
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
mockk-agent = { group = "io.mockk", name = "mockk-agent", version.ref = "mockk"}

#robolectric
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }

#squareup okhttp3
squareup-okhttp3-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version.ref = "squareupOkhttp3" }
sqaureup-okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor" }
sqaureup-okhttp3-okhttp = { group = "com.squareup.okhttp3", name = "okhttp" }
#squareup moshi
squareup-moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "squareupMoshi" }
squareup-moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "squareupMoshi" }
#sqaureup retrofit2
squareup-retrofit2-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "squareupRetrofit2" }
squareup-retrofit2-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "squareupRetrofit2" }
sqaureup-retrofit2-converter-scalars = { group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "squareupRetrofit2" }
squareup-retrofit2-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "squareupRetrofit2" }

timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
#CLASSPATH PLUGIN

jacoco = { group = "org.jacoco", name = "org.jacoco.core", version.ref = "jacoco" }
jetbrains-kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
jetbrains-kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }

navigation-safeargs = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigationSafeArgs" }

[bundles]
#implementation(libs.androidx.compose.ui)
#    implementation(libs.androidx.compose.ui.graphics)
#    implementation(libs.androidx.compose.ui.tooling.preview)
#    implementation(libs.androidx.compose.material3)
#    implementation(libs.androidx.lifecycle.viewmodel.compose)
#    implementation(libs.androidx.activity.compose)
androidx-compose = ["androidx-compose-ui", "androidx-compose-ui-graphics", "androidx-compose-ui-tooling-preview",
    "androidx-compose-material3", "androidx-activity-compose", "androidx-lifecycle-viewmodel-compose"]
androidx-lifecycle = ["androidx-lifecycle-livedata-ktx", "androidx-lifecycle-viewmodel-ktx", "androidx-lifecycle-runtime-ktx",
    "androidx-lifecyle-livedata-core-ktx", "androidx-lifecyle-reactivestreams-ktx"]
androidx-navigation = ["androidx-navigation-dynamic-features-fragment", "androidx-navigation-fragment-ktx", "androidx-navigation-ui-ktx"]
androidx-room-sqlite = ["androidx-room-ktx", "androidx-room-runtime", "androidx-sqlite-ktx"]

firebase-analytics-crashlytics-ktx = ["firebase-analytics-ktx", "firebase-crashlytics-ktx"]

sqaureup-okhttp-logging-interceptor = ["sqaureup-okhttp3-okhttp", "sqaureup-okhttp3-logging-interceptor"]
squareup-retrofit2-moshi-gson-scalars = ["squareup-retrofit2-retrofit", "squareup-retrofit2-converter-moshi", "squareup-retrofit2-converter-gson",
    "sqaureup-retrofit2-converter-scalars", "squareup-moshi-kotlin", "squareup-moshi-kotlin-codegen", "google-code-gson"]

[plugins]

android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }

crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlyticsPlugin" }

dagger-hilt-android-plugin = { id = "com.google.dagger.hilt.android", version.ref = "googleDaggerHilt" }

google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }

jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
jetbrains-kotlin-plugin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }

ksp = { id = "com.google.devtools.ksp", version.ref = "kspPlugin" }

navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigationSafeArgs" }

sonarqube = { id = "org.sonarqube", version.ref = "sonarqubePlugin" }
